# ==========================================
# ESTÁGIO 1: BASE E DEPENDÊNCIAS (CACHE)
# ==========================================
FROM node:22-alpine AS base

LABEL maintainer="Ambiente node express"
LABEL description="Ambiente de desenvolvimento Node.js para Express"

WORKDIR /app

# Atualiza o npm para a versão mais recente
RUN npm install -g npm@latest --silent

# Copia os arquivos de lock e manifesto PRIMEIRO
# COPY package*.json ./

# Instala as dependências aqui no build! O Docker vai fazer cache dessa camada.
# RUN npm install --silent

# ==========================================
# ESTÁGIO 2: DESENVOLVIMENTO (Docker)
# ==========================================
FROM base AS dev

EXPOSE 3000

# Como a instalação já foi feita no Estágio 1, o container liga instantaneamente!
# O código real será injetado via Bind Mount do compose.yaml
CMD ["npm", "run", "dev"]

# ==========================================
# ESTÁGIO 3: PRODUÇÃO (Deploy)
# ==========================================
FROM base AS prod

# Aqui o Bind Mount não existe, então copiamos o código para dentro da imagem
COPY . .

# Se houver script build: RUN npm run build
EXPOSE 3000

CMD ["npm", "start"]
