name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5

      # Fixe para uma versão recente do action (ex.: v0.9.1) ou use @latest
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      # Opcional: reduzir conflitos se houver atualizações concorrentes
      - name: Pull latest (fast-forward only)
        run: git pull --ff-only || true

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"
          git add -A .
          if git commit -m ":white_check_mark: Gerado gráfico 3D de perfil"; then
            git push
          fi
