# GitHub Action para gerar múltiplas versões da cobrinha com diferentes estilos estéticos
# e converter automaticamente os SVGs em GIFs de alta qualidade.

name: Generate Snake

on:
  schedule:
    # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - uses: actions/checkout@v3

      # Gera as diferentes versões da cobrinha (SVG)
      - uses: Platane/snk@v3.3.0
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-snake-neon.svg?color_snake=purple&color_dots=%2322223b,%233a0ca3,%23f72585,%23ffbe0b,%2300f2ea
            dist/github-snake-ocean.svg?color_snake=orange&color_dots=%23bfd6f6,%238dbdff,%2364a1f4,%234b91f1,%233c7dd9
            dist/github-snake-rainbow.svg?color_snake=%23ff4da6&color_dots=%23ff595e,%23ffca3a,%238ac926,%231982c4,%236a4c93
            dist/github-snake-mint.svg?color_snake=%2350fa7b&color_dots=%23f1faee,%23a8dadc,%23457b9d,%231d3557,%23e63946
            dist/github-snake-dracula.svg?color_snake=%23ff79c6&color_dots=%23282a36,%2344475a,%236272a4,%23bd93f9,%23ff5555
            dist/github-snake-autumn.svg?color_snake=%238d5524&color_dots=%23ffd6a5,%23fdffb6,%23caff70,%239bf6ff,%23ffc6ff
            dist/github-snake-sky.svg?color_snake=%2387cefa&color_dots=%23e0f7fa,%23b2ebf2,%234fc3f7,%232196f3,%230d47a1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Mostra o status da construção
      - name: Show build status
        run: git status

      # Instala o ImageMagick e converte os SVGs em GIFs de alta qualidade
      - name: Convert SVGs to GIFs
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          # Corrige permissões antes de criar a pasta gif
          sudo chmod -R 777 dist
          mkdir -p dist/gif
          for file in dist/*.svg; do
            name=$(basename "$file" .svg)
            echo "Convertendo $file para GIF..."
            convert -background none -density 400 -resize 800x800 -quality 100 "$file" "dist/gif/${name}.gif"
          done


      # Mostra os arquivos convertidos
      - name: List output files
        run: ls -R dist

      # Faz o push dos SVGs e GIFs para a branch "output"
      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake SVGs and GIF animations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
