# Este é um fluxo de trabalho básico para ajudá-lo a começar com Actions

name: Generate Snake

# Controla quando a ação será executada. Esta ação é executada a cada 6 horas.

on:
  schedule:
      # A cada 6 horas
    - cron: "0 */6 * * *"

# Este comando nos permite executar a ação automaticamente a partir da guia Actions.
  workflow_dispatch:

# A sequência de execuções neste fluxo de trabalho:
jobs:
  # Este fluxo de trabalho contém um único job chamado "build".
  build:
    # O tipo de runner no qual o job será executado.
    runs-on: ubuntu-latest

    # Os steps representam uma sequência de tarefas que serão executadas como parte do job.
    steps:

    # Faz o checkout do repositório sob $GITHUB_WORKSHOP, para que o job possa acessá-lo.
      - uses: actions/checkout@v2

    # Gera a animacao da cobrinha
      - uses: Platane/snk@main
        id: snake-gif
        with:
          github_user_name: LKSFerreira
          # As próximas duas linhas geram os arquivos em uma branch chamada "output". Isso impede que a branch principal fique confusa.
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

     # Mostra o status da construção. Torna mais fácil para depurar (se houver algum problema).
      - run: git status

      # Faz um Push nas alterações
      - name: Push changes
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # A branch de saída que mencionamos acima.
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
