name: Generate Snake

on:
  schedule:
    # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - uses: actions/checkout@v3

      # Gera as diferentes versões da cobrinha usando a nomenclatura pedida
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # --------- PADRÕES ---------
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

            # --------- LKS FERREIRA NEON RETRO ---------
            dist/github-contribution-grid-snake-lks-neon.svg?color_snake=purple&color_dots=#22223b,#3a0ca3,#f72585,#ffbe0b,#00f2ea&color_dots_ate=#0d1117


            # --------- NEON RETRO ---------
            dist/github-contribution-grid-snake-neon.svg?color_snake=purple&color_dots=#22223b,#3a0ca3,#f72585,#ffbe0b,#00f2ea

            # --------- OCEAN ---------
            dist/github-contribution-grid-snake-ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

            # --------- RAINBOW ---------
            dist/github-contribution-grid-snake-rainbow.svg?color_snake=#ff4da6&color_dots=#ff595e,#ffca3a,#8ac926,#1982c4,#6a4c93

            # --------- MINT CANDY ---------
            dist/github-contribution-grid-snake-mint.svg?color_snake=#50fa7b&color_dots=#f1faee,#a8dadc,#457b9d,#1d3557,#e63946

            # --------- DRACULA THEME ---------
            dist/github-contribution-grid-snake-dracula.svg?color_snake=#ff79c6&color_dots=#282a36,#44475a,#6272a4,#bd93f9,#ff5555

            # --------- AUTUMN ---------
            dist/github-contribution-grid-snake-autumn.svg?color_snake=#8d5524&color_dots=#ffd6a5,#fdffb6,#caff70,#9bf6ff,#ffc6ff

            # --------- SKY CLOUD ---------
            dist/github-contribution-grid-snake-sky.svg?color_snake=#87cefa&color_dots=#e0f7fa,#b2ebf2,#4fc3f7,#2196f3,#0d47a1

            # --------- DARK FOREST ---------
            dist/github-contribution-grid-snake-forest.svg?color_snake=#228b22&color_dots=#3e4e50,#264653,#2a9d8f,#e9c46a,#f4a261

            # --------- FIRE SUNSET ---------
            dist/github-contribution-grid-snake-sunset.svg?color_snake=#ff5400&color_dots=#ffb703,#fb8500,#ff006e,#d90429,#3a86ff

            # --------- ICEBERG ---------
            dist/github-contribution-grid-snake-ice.svg?color_snake=#bde0fe&color_dots=#0b3d91,#1e6091,#76c7c0,#c0e2e7,#fbf8cc

            # --------- RETRO GAME ---------
            dist/github-contribution-grid-snake-retro.svg?color_snake=#32cd32&color_dots=#000000,#5c5757,#ffd700,#e57373,#8bc34a

            # --------- SOLARIZED DARK ---------
            dist/github-contribution-grid-snake-solarized.svg?color_snake=#b58900&color_dots=#002b36,#073642,#586e75,#839496,#eee8d5

            # --------- NORD ---------
            dist/github-contribution-grid-snake-nord.svg?color_snake=#81a1c1&color_dots=#2e3440,#3b4252,#434c5e,#eceff4,#a3be8c

            # --------- AYU MIRAGE ---------
            dist/github-contribution-grid-snake-ayu.svg?color_snake=#ffcc66&color_dots=#232634,#252b3e,#7a7c94,#abb0c6,#ffd580

            # --------- HALLOWEEN ---------
            dist/github-contribution-grid-snake-halloween.svg?color_snake=#ff7518&color_dots=#121212,#fb743e,#ffd166,#ffb563,#88292f

            # --------- SWEET NIGHT ---------
            dist/github-contribution-grid-snake-night.svg?color_snake=#633f85&color_dots=#232946,#393e46,#a6b1e1,#f4e2d8,#f7f6e7

            # --------- PASTEL DREAM ---------
            dist/github-contribution-grid-snake-pastel.svg?color_snake=#f6abb6&color_dots=#ffdde4,#c1c8e4,#b5ead7,#ffdac1,#ffb7b2

            # --------- CYBER BLUE ---------
            dist/github-contribution-grid-snake-cyber.svg?color_snake=#039be5&color_dots=#212121,#353b48,#0abde3,#00cec9,#dff9fb

            # --------- GALAXY ---------
            dist/github-contribution-grid-snake-galaxy.svg?color_snake=#9d4edd&color_dots=#22223b,#3f37c9,#4895ef,#f72585,#b5179e

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Mostra o status da construção
      - name: Show build status
        run: git status

      # Push dos novos arquivos para a branch "output"
      - name: Push new files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
